
theme: jekyll-theme-cayman
title: "Basicis - Core ©"
description: "As the name says, it is made to be basic and direct."
logo: "https://raw.githubusercontent.com/basicis/core/master/storage/img/logo.png"
show_downloads: true
staticman:
  branch: "gh-pages"