name: Unit Testing
on:
  pull_request:
    branchs: 
      - [master]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout ✔
        uses: actions/checkout@v2
      
      - name: Composer 🔧	
        uses: php-actions/composer@v1

      - name: PHPUnit Tests 🧪
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/test.sh